%YAML:1.0


image_topic: "/cam0/image_raw"
output_path: "/home/zx/Output/Line_VIO"
#camera calibration 
model_type: PINHOLE
camera_name: camera
width: 752
height: 480
#distortion_parameters:
k1: -2.917e-01
k2: 8.228e-02
p1: 5.333e-05
p2: -1.578e-04
#projection_parameters:
fx: 4.616e+02
fy: 4.603e+02
cx: 3.630e+02
cy: 2.481e+02

   
#additional transform for bais
initialRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   # data: [1, 0, 0,
   #        0, 1, 0,
   #        0, 0, 1]
   data: [0.9958,   -0.0907,   -0.0072,
          0.0909,    0.9953,    0.0325,
          0.0042,   -0.0331,    0.9994]

#Translation from first body frame to world frame
initialTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   # data: [0.0, 0.0, 0.0]
   data: [0.2072, -0.0870, 0.0543]

   
# Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.0148655429818, -0.999880929698, 0.00414029679422,
           0.999557249008, 0.0149672133247, 0.025715529948, 
           -0.0257744366974, 0.00375618835797, 0.999660727178]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.0216401454975,-0.064676986768, 0.00981073058949]

#line feature detection parameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, turn on equalize to find enough features

undisKeyLine: 0

# optimization parameters
iterations: 1

savefile: 0
threshold: 35
lamda: 0.1745 #0.1745
show: 1

PL_Calculation: 0

per_inliers: 10
length_threshold: 90    # length thershold of line features
lambda: 0.1745 #0.1745
overlap_th: 0.5  #0.45
dist_th: 50
degree_th: 0.1 # all angle is rad
angle_th: 0.1 # 0.3491 20 degree
outlier_th: 1   # or AveOverlap_in and 0.995